services:
    redis:
        image: redis:7
        ports:
            - "6380:6379"

    horizon:
        build: .
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            APP_ENV: local
            APP_KEY: ${APP_KEY}
            QUEUE_CONNECTION: redis
            REDIS_HOST: redis
            REDIS_PORT: 6379
            DB_HOST: host.docker.internal
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        command: bash -lc "composer install --no-interaction && php artisan horizon"
        depends_on:
            - redis
